# Generated by Django 5.2.10 on 2026-02-02 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technical_details', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature/Module',
                'verbose_name_plural': 'Features/Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FutureScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('reconstruction', 'Reconstruction Pipeline'), ('editing', 'Editing Pipeline'), ('system', 'System-Level'), ('research', 'Research Direction')], max_length=20)),
                ('icon', models.CharField(default='fas fa-rocket', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Future Scope',
                'verbose_name_plural': 'Future Scope Items',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('reconstruction', 'Reconstruction Pipeline'), ('editing', 'Editing Pipeline'), ('system', 'System-Level')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Limitation',
                'verbose_name_plural': 'Limitations',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technical_details', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-arrow-right', max_length=50)),
            ],
            options={
                'verbose_name': 'Methodology Step',
                'verbose_name_plural': 'Methodology Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'Project Objective',
                'verbose_name_plural': 'Project Objectives',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Single Image 3D Reconstruction', max_length=300)),
                ('short_title', models.CharField(default='SI3DR', max_length=100)),
                ('tagline', models.CharField(default='Generating detailed 3D models from a single 2D image using AI', max_length=500)),
                ('abstract', models.TextField(help_text='Main abstract of the project')),
                ('problem_statement', models.TextField(help_text='Detailed problem statement')),
                ('institution', models.CharField(default='Tribhuvan University, Institute of Engineering, Pulchowk Campus', max_length=300)),
                ('department', models.CharField(default='Department of Electronics and Computer Engineering', max_length=200)),
                ('submission_date', models.CharField(default='December 2025', max_length=50)),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image for homepage', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Project Information',
                'verbose_name_plural': 'Project Information',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric_value', models.CharField(blank=True, max_length=50)),
                ('metric_label', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Result/Outcome',
                'verbose_name_plural': 'Results/Outcomes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('category', models.CharField(default='General', help_text='e.g., Reconstruction, Editing, Results', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g., Assoc. Prof. Dr.', max_length=100)),
                ('role', models.CharField(default='Project Supervisor', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supervisors/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phase_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, help_text='Additional technical details')),
                ('icon', models.CharField(default='fas fa-cog', max_length=50)),
            ],
            options={
                'verbose_name': 'System Phase',
                'verbose_name_plural': 'System Phases',
                'ordering': ['phase_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(default='Developer', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework/Library'), ('tool', 'Tool/Platform'), ('model', 'ML Model'), ('hardware', 'Hardware')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class or custom icon', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tech_logos/')),
                ('url', models.URLField(blank=True, help_text='Official website URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order'],
            },
        ),
    ]
