# ==============================================================================
# FRONTEND CONFIGURATION 
# Variables and settings for communicating with the external Cloudflare Tunnel
# ==============================================================================

# This is the public URL generated by your Lightning AI Backend's Cloudflare Tunnel
# Example: "https://your-random-words.trycloudflare.com"
# When you start `api_server.py` on your backend, paste the TryCloudflare URL here.
HUNYUAN_BACKEND_URL = "https://consisting-del-suse-dylan.trycloudflare.com"

# This is the public URL generated by your LOCAL Frontend's Cloudflare Tunnel
# Expose your local Django server by opening a new terminal and running:
# `cloudflared tunnel --url http://127.0.0.1:8000`
# Paste that new TryCloudflare link here so the remote backend knows where to upload the finished GLBs!
FRONTEND_PUBLIC_URL = "https://designation-freely-mug-picked.trycloudflare.com"

# ==============================================================================
# AWS S3 STORAGE CONFIGURATION
# ==============================================================================
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_REGION_NAME = ""
AWS_S3_BUCKET_NAME = "si3dr-3d-assets-bucket"  # Must match backend config
